In [1]:
import glob
from general import *
from generation import *
from storage import *
from systemCopy1 import *
from copy import deepcopy

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
load_mw = Load_Data(years=2033).load_MW
#load_mw['load_MW'] = 20

In [5]:
load_mw

                       load_MW
Date/time
2033-01-01 00:30:00  61.873062
2033-01-01 01:30:00  62.962898
2033-01-01 02:30:00  62.851831
2033-01-01 03:30:00  62.807868
2033-01-01 04:30:00  64.001828
...                        ...
2033-12-31 19:30:00  63.699321
2033-12-31 20:30:00  63.543213
2033-12-31 21:30:00  63.384774
2033-12-31 22:30:00  62.771989
2033-12-31 23:30:00  62.613551

[8760 rows x 1 columns]

In [6]:
Kfiles = glob.glob('/projects/wg-ASGARD/weather_data/KAFB/*2013*')

In [7]:
KAFB_site = Site('KAFB',Weather_Data(Kfiles),-7)

In [8]:
#modify CSP tower

In [10]:
csp_config = {'thermal_power_MW_t': 100,
          'power_rating_MW_e': 50,
          'dni_des':950,
          'tower_height_m': 117,
          'receiver_width_m':5,
          'receiver_height_m':5,
          'accept_ang_y':180,
          'accept_ang_x':180,
          'heliostat_width_m':5,
          'heliostat_height_m':5,
          'field_max_scaled_rad':8,
          'layout_method':'Radial Stagger',
          'field_shape':'Hexagon',
          'interaction_limit':50,
          'row_spacing_x':1.5,
          'row_spacing_y':1.5,
          'receiver_dT': 1,
          'media_cp': 1,
          'optical_height_m': 1,}

In [11]:
ASGARD_CSP = CSP_System(name='ASGARD_CSP',
                        site = KAFB_site,
                        config = csp_config,
                        off_grid_operation = True)

In [12]:
# loads the above csp system. will need to comment this block if you change the above.
# import pickle
# with open('/projects/wg-ASGARD/csp_obj/csp_100MWhth_50MW.pkl','rb') as file:
#     ASGARD_CSP = pickle.load(file)

In [13]:
ASGARD_TES = TES_System(name='ASGARD_TES',
                        site = KAFB_site,
                        capacity_MWh_e = 570,
                        power_rating_MW_e = 50,
                        power_minimum_MW_e = 0,
                        percent_discharge_depth = 95,
                        percent_heat_loss_daily = 1,
                        charge_rate_CSP_MW_t = .6*143,
                        charge_efficiency_t2TES = .98,
                        charge_rate_resistive_MW_e = None,
                        charge_efficiency_e2TES = .98,
                        systems_charging = ['ASGARD_CSP'],
                        start_full = True,
                        off_grid_operation = True,
                        DOE_2030_targets = False,
                        dT_s = 200, # [C] dT across storage bins
                        cp_s = 1.15, # [kJ/kgK] storage media specific heat
                        rho_s = 2000) # [kg/m3] media bulk density)

In [14]:
ASGARD_systems = ['ASGARD_TES', 'ASGARD_CSP']
# ASGARD_systems = ['ASGARD_PV','ASGARD_CSP','ASGARD_TES','ASGARD_BES']

In [15]:
#need to change site for this configuration.
# ASGARD_CSP.site = KAFB_site

In [16]:
systems=ASGARD_systems
ASGARD = System(load_MW = load_mw, time_series = None,
             systems_load_order = [globals()[sys] for sys in systems])

8760

In [17]:
ts = ASGARD.timeseries

In [18]:
ts.columns

Index(['load_MW', 'target_load_MW', 'grid_to_load_MWh_e',
       'unmet_target_load_MWh_e', 'export_energy_MWh_e',
       'electricity_sale_in_hour', 'ASGARD_CSP_heat_MW_t',
       'ASGARD_CSP_heat_unused_MWh_t', 'ASGARD_CSP_to_ASGARD_TES_MWh_t',
       'ASGARD_TES_MWh_t', 'ASGARD_TES_thermal_loss_MWh_t',
       'CSP_System_to_ASGARD_TES_MWh_t', 'ASGARD_TES_to_load_MWh_t',
       'ASGARD_TES_to_load_MWh_e', 'ASGARD_TES_to_load_MWh_gas_e',
       'ASGARD_TES_to_load_MWh_gas_t', 'ASGARD_TES_to_load_MWh_gas_kg',
       'ASGARD_TES_gas_dollars', 'ASGARD_TES_frac_nogas',
       'ASGARD_TES_frac_gas', 'KAFB_POI_MW', 'unmet_load_MWh_e'],
      dtype='object')

In [19]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
ts.head(50)

,load_MW,target_load_MW,grid_to_load_MWh_e,unmet_target_load_MWh_e,export_energy_MWh_e,electricity_sale_in_hour,ASGARD_CSP_heat_MW_t,ASGARD_CSP_heat_unused_MWh_t,ASGARD_CSP_to_ASGARD_TES_MWh_t,ASGARD_TES_MWh_t,ASGARD_TES_thermal_loss_MWh_t,CSP_System_to_ASGARD_TES_MWh_t,ASGARD_TES_to_load_MWh_t,ASGARD_TES_to_load_MWh_e,ASGARD_TES_to_load_MWh_gas_e,ASGARD_TES_to_load_MWh_gas_t,ASGARD_TES_to_load_MWh_gas_kg,ASGARD_TES_gas_dollars,ASGARD_TES_frac_nogas,ASGARD_TES_frac_gas,KAFB_POI_MW,unmet_load_MWh_e
Date/time,,,,,,,,,,,,,,,,,,,,,,
2033-01-01 00:30:00,61.873062,None,0.000000,0.0,0,0.000000,0.0,0.0,0,570.000000,0.000000,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,NaN
2033-01-01 01:30:00,62.962898,None,12.962898,NaN,0,3500.000000,0.0,0.0,0,479.278288,0.237500,0,90.484212,50.00000,0,0,0,0,1.000000,1.000000,50.00000,12.962898
2033-01-01 02:30:00,62.851831,None,12.851831,NaN,0,3500.000000,0.0,0.0,0,388.431581,0.199699,0,90.647008,50.00000,0,0,0,0,1.000000,1.000000,50.00000,12.851831
2033-01-01 03:30:00,62.807868,None,12.807868,NaN,0,3500.000000,0.0,0.0,0,297.398650,0.161846,0,90.871085,50.00000,0,0,0,0,1.000000,1.000000,50.00000,12.807868
2033-01-01 04:30:00,64.001828,None,14.001828,NaN,0,3500.000000,0.0,0.0,0,206.217739,0.123916,0,91.056994,50.00000,0,0,0,0,1.000000,1.000000,50.00000,14.001828
2033-01-01 05:30:00,64.496998,None,14.496998,NaN,0,3500.000000,0.0,0.0,0,114.849726,0.085924,0,91.282089,50.00000,0,0,0,0,1.000000,1.000000,50.00000,14.496998
2033-01-01 06:30:00,63.874565,None,16.694375,NaN,0,3302.613327,0.0,0.0,0,28.500000,0.047854,0,86.301872,47.18019,0,0,0,0,0.943604,0.943604,47.18019,16.694375
2033-01-01 07:30:00,64.300318,None,64.300318,NaN,0,0.000000,0.0,0.0,0,28.488125,0.011875,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,64.300318
2033-01-01 08:30:00,63.425673,None,63.425673,NaN,0,0.000000,0.0,0.0,0,28.476255,0.011870,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.425673
2033-01-01 09:30:00,63.805149,None,63.805149,NaN,0,0.000000,0.0,0.0,0,28.464390,0.011865,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.805149
2033-01-01 10:30:00,63.323862,None,63.323862,NaN,0,0.000000,0.0,0.0,0,28.452530,0.011860,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.323862
2033-01-01 11:30:00,63.057767,None,63.057767,NaN,0,0.000000,0.0,0.0,0,28.440674,0.011855,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.057767
2033-01-01 12:30:00,62.215515,None,62.215515,NaN,0,0.000000,0.0,0.0,0,28.428824,0.011850,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,62.215515
2033-01-01 13:30:00,62.754649,None,62.754649,NaN,0,0.000000,0.0,0.0,0,28.416979,0.011845,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,62.754649
2033-01-01 14:30:00,62.750021,None,62.750021,NaN,0,0.000000,0.0,0.0,0,28.405138,0.011840,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,62.750021
2033-01-01 15:30:00,62.715313,None,62.715313,NaN,0,0.000000,0.0,0.0,0,28.393303,0.011835,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,62.715313
2033-01-01 16:30:00,62.826379,None,62.826379,NaN,0,0.000000,0.0,0.0,0,28.381472,0.011831,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,62.826379
2033-01-01 17:30:00,63.661688,None,63.661688,NaN,0,0.000000,0.0,0.0,0,28.369647,0.011826,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.661688
2033-01-01 18:30:00,64.015711,None,64.015711,NaN,0,0.000000,0.0,0.0,0,28.357826,0.011821,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,64.015711
2033-01-01 19:30:00,63.856054,None,63.856054,NaN,0,0.000000,0.0,0.0,0,28.346010,0.011816,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.856054
2033-01-01 20:30:00,64.191566,None,64.191566,NaN,0,0.000000,0.0,0.0,0,28.334200,0.011811,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,64.191566
2033-01-01 21:30:00,64.112894,None,64.112894,NaN,0,0.000000,0.0,0.0,0,28.322394,0.011806,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,64.112894
2033-01-01 22:30:00,63.802835,None,63.802835,NaN,0,0.000000,0.0,0.0,0,28.310593,0.011801,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.802835
2033-01-01 23:30:00,63.534425,None,63.534425,NaN,0,0.000000,0.0,0.0,0,28.298797,0.011796,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.534425
2033-01-02 00:30:00,63.004547,None,63.004547,NaN,0,0.000000,0.0,0.0,0,28.287005,0.011791,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.004547
2033-01-02 01:30:00,63.187344,None,63.187344,NaN,0,0.000000,0.0,0.0,0,28.275219,0.011786,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.187344
2033-01-02 02:30:00,63.527483,None,63.527483,NaN,0,0.000000,0.0,0.0,0,28.263438,0.011781,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.527483
2033-01-02 03:30:00,63.414104,None,63.414104,NaN,0,0.000000,0.0,0.0,0,28.251661,0.011776,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.414104
2033-01-02 04:30:00,65.482709,None,65.482709,NaN,0,0.000000,0.0,0.0,0,28.239890,0.011772,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,65.482709
2033-01-02 05:30:00,66.468421,None,66.468421,NaN,0,0.000000,0.0,0.0,0,28.228123,0.011767,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.468421
2033-01-02 06:30:00,66.260172,None,66.260172,NaN,0,0.000000,0.0,0.0,0,28.216361,0.011762,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.260172
2033-01-02 07:30:00,66.533209,None,66.533209,NaN,0,0.000000,0.0,0.0,0,28.204605,0.011757,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.533209
2033-01-02 08:30:00,66.688239,None,66.688239,NaN,0,0.000000,0.0,0.0,0,28.192853,0.011752,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.688239
2033-01-02 09:30:00,66.803933,None,66.803933,NaN,0,0.000000,0.0,0.0,0,28.181106,0.011747,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.803933
2033-01-02 10:30:00,65.832105,None,65.832105,NaN,0,0.000000,0.0,0.0,0,28.169364,0.011742,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,65.832105
2033-01-02 11:30:00,66.510070,None,66.510070,NaN,0,0.000000,0.0,0.0,0,28.157626,0.011737,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.510070
2033-01-02 12:30:00,65.940857,None,65.940857,NaN,0,0.000000,0.0,0.0,0,28.145894,0.011732,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,65.940857
2033-01-02 13:30:00,66.290252,None,66.290252,NaN,0,0.000000,0.0,0.0,0,28.134167,0.011727,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.290252
2033-01-02 14:30:00,66.174558,None,66.174558,NaN,0,0.000000,0.0,0.0,0,28.122444,0.011723,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.174558
2033-01-02 15:30:00,66.012587,None,66.012587,NaN,0,0.000000,0.0,0.0,0,28.110726,0.011718,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.012587
2033-01-02 16:30:00,65.325366,None,65.325366,NaN,0,0.000000,0.0,0.0,0,28.099013,0.011713,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,65.325366
2033-01-02 17:30:00,67.014496,None,67.014496,NaN,0,0.000000,0.0,0.0,0,28.087306,0.011708,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,67.014496
2033-01-02 18:30:00,66.313391,None,66.313391,NaN,0,0.000000,0.0,0.0,0,28.075603,0.011703,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,66.313391
2033-01-02 19:30:00,65.931601,None,65.931601,NaN,0,0.000000,0.0,0.0,0,28.063904,0.011698,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,65.931601
2033-01-02 20:30:00,65.397096,None,65.397096,NaN,0,0.000000,0.0,0.0,0,28.052211,0.011693,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,65.397096
2033-01-02 21:30:00,64.855649,None,64.855649,NaN,0,0.000000,0.0,0.0,0,28.040523,0.011688,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,64.855649
2033-01-02 22:30:00,64.279493,None,64.279493,NaN,0,0.000000,0.0,0.0,0,28.028839,0.011684,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,64.279493
2033-01-02 23:30:00,63.705652,None,63.705652,NaN,0,0.000000,0.0,0.0,0,28.017160,0.011679,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.705652
2033-01-03 00:30:00,63.853740,None,63.853740,NaN,0,0.000000,0.0,0.0,0,28.005487,0.011674,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.853740
2033-01-03 01:30:00,63.578389,None,63.578389,NaN,0,0.000000,0.0,0.0,0,27.993818,0.011669,0,0.000000,0.00000,0,0,0,0,0.000000,0.000000,0.00000,63.578389